org: anguspbezzina
app: personality-scraper
service: personality-scraper

useDotenv: true

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs20.x
  httpApi:
    cors: true

plugins:
  - serverless-offline

functions:
  chatbot:
    handler: dist/chatbot.handler
    events:
      - httpApi:
          path: /chatbot
          method: post
    environment:
      LANGCHAIN_API_KEY: "${env:LANGCHAIN_API_KEY}"
      LANGCHAIN_TRACING_V2: "${env:LANGCHAIN_TRACING_V2}"
      LANGCHAIN_CALLBACKS_BACKGROUND: "${env:LANGCHAIN_CALLBACKS_BACKGROUND}"
      OPENAI_API_KEY: "${env:OPENAI_API_KEY}"

custom:
  serverless-offline:
    babelOptions:
      presets: ["env"]
